import { WeddingData, WeddingTheme } from '../types/wedding';

export const WEDDING_THEMES: WeddingTheme[] = [
  {
    id: 'emerald-gold',
    name: 'Zamrud Emerald & Gold',
    primary: '#064e3b',
    primaryDark: '#022c22',
    accentGold: '#d4af37',
    accentGoldLight: '#fbe094',
    bgGradient: 'from-emerald-950 via-teal-950 to-slate-950',
    cardBg: 'rgba(6, 78, 59, 0.45)',
    textPrimary: '#fef3c7',
    textMuted: '#d1fae5',
    envelopeColor: '#043527',
    waxSealColor: '#b45309'
  },
  {
    id: 'ruby-burgundy',
    name: 'Yaqoot Ruby & Rose Gold',
    primary: '#4a0404',
    primaryDark: '#2b0202',
    accentGold: '#e5a93c',
    accentGoldLight: '#fed7aa',
    bgGradient: 'from-rose-950 via-amber-950 to-neutral-950',
    cardBg: 'rgba(74, 4, 4, 0.45)',
    textPrimary: '#ffedd5',
    textMuted: '#fecdd3',
    envelopeColor: '#3d0202',
    waxSealColor: '#991b1b'
  },
  {
    id: 'midnight-sapphire',
    name: 'Kohl Midnight Sapphire & Gold',
    primary: '#0f172a',
    primaryDark: '#020617',
    accentGold: '#e6c66e',
    accentGoldLight: '#fef08a',
    bgGradient: 'from-slate-950 via-sky-950 to-neutral-950',
    cardBg: 'rgba(15, 23, 42, 0.55)',
    textPrimary: '#f8fafc',
    textMuted: '#cbd5e1',
    envelopeColor: '#0b1329',
    waxSealColor: '#ca8a04'
  },
  {
    id: 'dusty-rose',
    name: 'Ward Rose & Champagne',
    primary: '#831843',
    primaryDark: '#500724',
    accentGold: '#d97706',
    accentGoldLight: '#fde68a',
    bgGradient: 'from-pink-950 via-rose-950 to-neutral-950',
    cardBg: 'rgba(80, 7, 36, 0.45)',
    textPrimary: '#ffe4e6',
    textMuted: '#fbcfe8',
    envelopeColor: '#4c051f',
    waxSealColor: '#b91c1c'
  },
  {
    id: 'ivory-noor',
    name: 'Noor Ivory & Antique Brass',
    primary: '#292524',
    primaryDark: '#1c1917',
    accentGold: '#b45309',
    accentGoldLight: '#fef3c7',
    bgGradient: 'from-amber-950/40 via-stone-900 to-stone-950',
    cardBg: 'rgba(28, 25, 23, 0.65)',
    textPrimary: '#fef3c7',
    textMuted: '#e7e5e4',
    envelopeColor: '#2d2218',
    waxSealColor: '#92400e'
  },
  {
    id: 'onyx-royal',
    name: 'Layl Onyx & Pure 24K Gold',
    primary: '#09090b',
    primaryDark: '#000000',
    accentGold: '#eab308',
    accentGoldLight: '#fef9c3',
    bgGradient: 'from-zinc-950 via-neutral-950 to-black',
    cardBg: 'rgba(18, 18, 18, 0.6)',
    textPrimary: '#fafafa',
    textMuted: '#e4e4e7',
    envelopeColor: '#121214',
    waxSealColor: '#a16207'
  }
];

export const AUDIO_PRESETS = [
  { id: 'nasheed-duff', name: 'Barakallahu Lakuma (Traditional Duff & Strings)', type: 'synth-duff' },
  { id: 'oud-ambient', name: 'Al-Noor Royal Oud & Ambient Harmony', type: 'synth-oud' },
  { id: 'peaceful-flute', name: 'Jannat Breeze (Bansuri & Reverb)', type: 'synth-flute' },
];

export const DEFAULT_WEDDING_DATA: WeddingData = {
  groomName: 'Zayan Farhan',
  groomPrefix: 'Engr.',
  groomParents: 'Mr. & Mrs. Farhan Tariq Al-Mansoor',
  brideName: 'Areesha Fatima',
  bridePrefix: 'Dr.',
  brideParents: 'Mr. & Mrs. Qasim Imran Siddiqui',
  invitationMessage: 'Together with their families, joyfully invite you to celebrate the sacred union of their beloved children and shower your du\'as and blessings upon them as they embark on this beautiful journey of love, faith, and companionship.',
  bismillahText: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ',
  quranicVerse: '“And among His signs is that He created for you mates from among yourselves that you may dwell in tranquility in them, and He has put between you affection and mercy.”',
  quranicReference: 'Surah Ar-Rum (30:21)',
  hijriDate: '18th Jumada al-Thani 1448 AH',
  mainWeddingDate: '2026-11-20',
  mainWeddingTime: '06:30 PM',
  mainCeremonyTitle: 'Sacred Nikah & Grand Feast',
  mainVenueName: 'The Grand Al-Miraj Royal Palace',
  mainVenueAddress: 'Crystal Ballroom, 452 Crescent Boulevard, Al-Zahra Gardens',
  mainMapsUrl: 'https://maps.google.com',
  couplePhotoUrl: '/src/assets/images/couple_portrait_default_1790615568777.jpg',
  photoStyle: 'arch',
  themeId: 'emerald-gold',
  rsvpPhone: '+91 9876543210',
  rsvpContactPerson: 'Tariq Siddiqui & Farhan Mansoor',
  musicTrackTitle: 'Barakallahu Lakuma (Halal Wedding Melodies)',
  isCustomMusic: false,
  selectedAudioPreset: 'nasheed-duff',
  envelopeGreeting: 'Specially Invited',
  envelopeInstruction: 'Tap Wax Seal To Unfold Invitation',
  countdownHeading: 'Counting Every Blessed Moment',
  countdownSubtitle: 'Auspicious Countdown To Nikah',
  scratchCardHeading: 'Interactive Heart Scratch Card',
  scratchCardSubtext: 'Scratch the golden heart with your finger or mouse to unveil the wedding date!',
  scratchCoverText: '✨ SCRATCH HERE ✨',
  scratchCoverSubtext: 'To Reveal The Wedding Date',
  scratchRevealedBadge: 'Date Revealed With Love!',
  ceremoniesSectionHeading: 'Sacred Ceremonies & Celebrations',
  ceremoniesSectionSubheading: 'Please grace every auspicious function with your heartfelt presence and du\'as',
  rsvpHeading: 'Kindly Grace Us With Your Presence',
  rsvpSubheading: 'Please confirm your attendance or send your heartful du\'as so we may welcome you with the warmest hospitality.',
  closingDuaArabic: 'بَارَكَ اللَّهُ لَكُمَا وَبَارَكَ عَلَيْكُمَا وَجَمَعَ بَيْنَكُمَا فِي خَيْرٍ',
  closingDuaTranslation: '“May Allah bless for you, and shower His blessings upon you, and bring you together in goodness.”',
  cardTitleBadge: 'With The Grace of Allah (SWT)',
  ceremonies: [
    {
      id: 'haldi',
      name: 'Haldi & Manjha Ceremony',
      arabicSubtitle: 'حفل الحناء والكركم',
      date: '2026-11-18',
      time: '11:00 AM - 03:00 PM',
      venueName: 'Gulmohar Courtyard, Mansoor Residence',
      venueAddress: 'Plot 12, Gulberg Estate, Floral Enclave',
      mapsUrl: 'https://maps.google.com',
      dressCode: 'Sunlit Yellow & Vibrant Florals',
      description: 'An auspicious morning of laughter, turmeric blessing paste, and traditional geet as the bride and groom get adorned with golden glow.',
      iconType: 'haldi'
    },
    {
      id: 'mehendi',
      name: 'Mehendi Ki Raat (Henna Evening)',
      arabicSubtitle: 'ليلة الحناء والبهجة',
      date: '2026-11-19',
      time: '07:00 PM onwards',
      venueName: 'The Royal Green Pavilion',
      venueAddress: 'Gate No. 3, Heritage Grand Lawns',
      mapsUrl: 'https://maps.google.com',
      dressCode: 'Emerald Green, Mint & Festive Lehengas',
      description: 'An enchanting musical evening filled with intricate henna artistry, fragrant jasmine gajras, and joyful family folk performances.',
      iconType: 'mehendi'
    },
    {
      id: 'nikah',
      name: 'Sacred Nikah & Baraat',
      arabicSubtitle: 'عقد القران المبارك والوليمة',
      date: '2026-11-20',
      time: '06:30 PM (Nikah Khutbah at 07:45 PM)',
      venueName: 'The Grand Al-Miraj Royal Palace',
      venueAddress: 'Crystal Ballroom, 452 Crescent Boulevard',
      mapsUrl: 'https://maps.google.com',
      dressCode: 'Royal Traditional Sherwanis & Modest Formals',
      description: 'The solemnization of marriage according to Sunnah, followed by exchange of vows, Qubool Hai, and a lavish royal banquet dinner.',
      iconType: 'nikah'
    },
    {
      id: 'walima',
      name: 'Grand Walima Reception',
      arabicSubtitle: 'حفل الوليمة المباركة',
      date: '2026-11-22',
      time: '08:00 PM onwards',
      venueName: 'Imperial Banquet & Convention Center',
      venueAddress: 'Tower Grand Hall, King Faisal Expressway',
      mapsUrl: 'https://maps.google.com',
      dressCode: 'Black Tie, Regal Formals & Pastel Silks',
      description: 'The auspicious Sunnah banquet hosted by the groom\'s family to celebrate and welcome the new bride with beloved relatives and friends.',
      iconType: 'walima'
    }
  ]
};
